Feat: Search Address
YAPP-19th/Android-Team-1-Frontend pull request #22
Opened 2021-11-20 07:16 UTC by jihee-dev

1. 주소 검색 기능 구현(도메인, 데이터, 프레젠테이션 모듈)
2. Di 추가(api 호출과 관련해서 중복된 부분이 있어 Qualifier도 추가하였습니다)
3. 검색 결과에 대해 검색어와 동일한 부분 강조 표시
4. 키워드 검색과 주소 검색을 나누지 않고 검색
  - 키워드와 주소 검색 결과를 모두 호출한 뒤, 더 많은 쪽의 결과를 먼저 보여주도록 구현하였습니다

p.s. 주소 상세 설정 화면 구현 전에 파일이 많아져서 풀 리퀘 먼저 올립니다! 이어서 주소 상세 화면 구현 이어가겠습니당

2021-11-20 07:18 UTC, jihee-dev commented
지금은 검색 결과 중 하나를 누르면 위도와 경도 정보를 로그로 찍도록 되어 있는데 이어서 개발하면서 상세 화면으로 이동하도록 수정할 예정입니다!

2021-11-21 04:30 UTC, LuvJoy commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/ui/location/search/LocationSearchFragment.kt
> +        }
repeatOnStarted 를 한번만 넣어주고 그 안에 collect를 2번 넣어줘도 됩니다!

2021-11-21 04:32 UTC, LuvJoy commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/ui/location/search/LocationSearchViewModel.kt
> +    }
ViewModel에서 onCleared 될때 job 객체를 null로 취소시켜주는게 메모리 누수를 방지할 수 있습니다.

2021-11-21 04:34 UTC, LuvJoy commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/adapter/LocationSearchAdapter.kt
> +    var listener: OnItemClickListener? = null
함수형으로 처리하면 좀 더 깔끔하게 처리할 수 있을것 같아요!

2021-11-21 04:41 UTC, jihee-dev commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/ui/location/search/LocationSearchFragment.kt
> +        }
이거 한 번만 넣어주고 하면 collect가 두 개가 안 되더라고요 분리해 주어야 잘 작동합니다 ㅠㅠ

2021-11-21 04:55 UTC, LuvJoy reviewed
HIlt 모듈별 정리까지 잘 해주신것 같아요! 
수정사항 몇가지를 적어봤는데 검토해주셨으면 좋겠습니다!

2021-11-21 04:55 UTC, LuvJoy commented on DeliBuddy/domain/src/main/java/yapp/android1/domain/interactor/usecase/SearchAddressUseCase.kt
> +        val response = addressRepository.fetchAddressByAddress(params)
굉장히 좋지 않은 네이밍 같아요

2021-11-21 04:55 UTC, LuvJoy commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/adapter/LocationSearchAdapter.kt
> +            listener = listener
한번에 모든걸 처리하는건 좋지만 가독성이 매우 떨어져 보여요

2021-11-21 04:55 UTC, LuvJoy commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/adapter/LocationSearchAdapter.kt
> +    var searchQuery = ""
이 친구를  Pair로 처리하면 좀 더 깔끔하지 않을까 하는 생각이 들어요!
Pair<검색어, 결과목록>

2021-11-21 05:01 UTC, LuvJoy commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/ui/location/search/LocationSearchFragment.kt
> +        }
아! 제가 착각했었네요! 지희님 말씀이 맞네요
이부분  repeat하고 collect를 한번에 쓸 수 있도록 개선해보겠습니다~

2021-11-21 05:01 UTC, jihee-dev commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/ui/location/search/LocationSearchFragment.kt
> +        }
감사합니당!

2021-11-22 03:11 UTC, jsh-me commented on DeliBuddy/.idea/misc.xml
> +        <entry key="app/src/main/res/drawable/delibuddy_btn_radius.xml" value="0.2212962962962963" />
gitignore에 idea 파일도 제외시키는게 어떨까요? @LuvJoy

2021-11-22 03:12 UTC, jsh-me commented on DeliBuddy/app/src/main/AndroidManifest.xml
> +            android:exported="false" />
`exported` 옵션이 무엇인가유!? 👀 어떤 목적을 위해 사용했는지 궁금해요 ㅎㅎ

2021-11-22 03:15 UTC, jsh-me commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/di/NetworkModule.kt
> +    @Singleton
이미 싱글톤 클래스로 구현되어있는데 annotation까지 붙여야 할까요 ? 🤔 없어도 괜찮을 것 같은 느낌!

2021-11-22 03:17 UTC, jsh-me commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/holder/AddressSearchViewHolder.kt
> +}
AddressSearchViewHolder 만을 위한 interface 일까요?
맞다면, 
1. 전역으로 빼내는 것보다는 `AddressSearchViewHolder` 안에 넣는게 좋을 것 같습니다.
2. 지금처럼 전역으로 선언해야 한다면 네이밍을 분명하게 짓는게 좋을 것 같습니다! 어떤 화면에 대한 인터페이스인지 감이 잘 안와서 네이밍 제안이 약간 어렵네요 ㅎㅎ

2021-11-22 03:22 UTC, jsh-me commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/ui/address/search/AddressSearchEvent.kt
> +    class SearchAddress(val query: String) : AddressSearchEvent()
딜리버디에서 `Event` 는 유저의 행위를 담고 있군용?? 맞나용?

2021-11-22 03:23 UTC, jsh-me commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/ui/address/search/AddressSearchFragment.kt
> +                addressAdapter.updateResult(it)
🙋‍♀️ 검색을 실패한 경우에는 어떻게 되나요 ?

2021-11-22 03:23 UTC, jsh-me commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/ui/address/search/AddressSearchFragment.kt
> +            }
🙋‍♀️ 검색을 실패한 경우에는 어떻게 되나요 ?

2021-11-22 03:25 UTC, jsh-me commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/ui/address/search/AddressSearchFragment.kt
> +                    val address = addressAdapter.getItem(position)
viewController 에서 adapter 로부터 받은 position을 item으로 변환하는 것 같네요! 차라리 position 을 받지말고, item 을 자체를 받는게 어떨까요?

2021-11-22 03:25 UTC, jsh-me commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/ui/address/search/AddressSearchViewModel.kt
> +    private var job: Job? = null
🙋‍♀️ `BaseViewModel` 에 job도 같이 구성하면 안될까요? 마치 rx의 disposavle 처럼.... @LuvJoy

2021-11-22 03:28 UTC, jsh-me commented on DeliBuddy/data/src/main/java/yapp/android1/data/entity/ResponseKeyword.kt
> +data class SameName(
`SameName`이 무엇을 의미하는 걸까유!?

2021-11-22 03:31 UTC, jsh-me commented on DeliBuddy/data/src/main/java/yapp/android1/data/entity/AddressMapper.kt
> +    fun responseToAddress(keywordDocument: KeywordDocument): Address {
entity는 suffix에 entity를 추가하는게 어떨까요? `Address` -> `AddressEntity`
이유는, data class 갯수가 많아질수록 & 다른이가 코드를 볼 때 어느것이 data layer 의 model이고, 어느것이 domain layer 의 entity인지 구별하기 힘들기 때문이에요

2021-11-22 03:31 UTC, jsh-me commented on DeliBuddy/data/src/main/java/yapp/android1/data/entity/AddressMapper.kt
> +    fun responseToAddress(keywordDocument: KeywordDocument): Address {
```suggestion
    fun toAddress(keywordDocument: KeywordDocument): Address {
```
이 정도로도 직관적이라 생각해서 제안드려용 ㅎㅎ

2021-11-22 03:32 UTC, jsh-me approved these changes
👍👍👍👍

2021-11-22 03:32 UTC, LuvJoy commented on DeliBuddy/.idea/misc.xml
> +        <entry key="app/src/main/res/drawable/delibuddy_btn_radius.xml" value="0.2212962962962963" />
넵 매번 놓치고 있었는데 예외에 추가해야 겠네요!

2021-11-22 03:34 UTC, LuvJoy commented on DeliBuddy/app/src/main/AndroidManifest.xml
> +            android:exported="false" />
exported는 다른 앱에서 해당 액티비티가 실행되느냐 안되느냐의 유무라고 알고 있네요
액티비티 만들면 다 세트로 붙여져 오는거 같네요!

2021-11-22 03:34 UTC, jsh-me commented on DeliBuddy/data/src/main/java/yapp/android1/data/entity/AddressMapper.kt
> +object AddressMapper {
```suggestion
object AddressDocumentResponseMapper {
```

훔..... 훔.... 어때요....?

2021-11-22 03:35 UTC, jsh-me commented on DeliBuddy/app/src/main/AndroidManifest.xml
> +            android:exported="false" />
아하!!!! 싱기하군요

2021-11-22 03:40 UTC, LuvJoy commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/ui/address/search/AddressSearchEvent.kt
> +    class SearchAddress(val query: String) : AddressSearchEvent()
넵! 맞습니다! 사실은 코드가 더 커지기 전에
모든 행위를 Action으로 두고 RenderAction(그리기)과 CallbackAction(행위)으로 행위로 나눠서
RenderAction은 Activity에서 처리해주고 CallbackAction은 ViewModel에서 처리 해주는 방향을 해볼까했었는데 
오버엔지니어링 느낌도 없지 않아 있고 괜히 다른분들도 적응하기 힘들고 진도가 느려질거 같아 일단은 현재 상태로 가려고 하고있습니다

2021-11-22 03:41 UTC, LuvJoy commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/ui/address/search/AddressSearchViewModel.kt
> +    private var job: Job? = null
넵 반영하겠습니다

2021-11-22 03:58 UTC, jsh-me commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/ui/address/search/AddressSearchEvent.kt
> +    class SearchAddress(val query: String) : AddressSearchEvent()
올... 재밌네욥 ㅋㅋ 굳굳 이해했습니다!

2021-11-22 08:18 UTC, LuvJoy requested changes
많은 양을 열심히 하시는 모습 보고 저도 많은 자극을 받고 있습니다!
화이팅입니다!

2021-11-22 08:18 UTC, LuvJoy commented on DeliBuddy/data/src/main/java/yapp/android1/data/repository/AddressRepositoryImpl.kt
> +    ): NetworkResult<List<Address>> = withContext(Dispatchers.IO) {
Retrofit은 내부적으로 IO로 처리가 되고 있어서 withContext를 사용할 필요가 없어요

2021-11-22 10:50 UTC, jihee-dev commented on DeliBuddy/app/src/main/AndroidManifest.xml
> +            android:exported="false" />
저도 자꾸 따라오길래 찾아봤었는데 액티비티 만들 때 같이 만들어져서 따로 안 건드린 부분이었어요!

2021-11-22 10:55 UTC, jihee-dev commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/di/NetworkModule.kt
> +    @Singleton
싱글톤 어노테이션을 없애도 된다는 말씀이신가요?

2021-11-22 10:55 UTC, jihee-dev commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/di/NetworkModule.kt
> +    @Singleton
제가 이 부분을 잘 몰라서.. 여쭤보는 거예요..!

2021-11-22 11:28 UTC, jihee-dev commented on DeliBuddy/data/src/main/java/yapp/android1/data/entity/ResponseKeyword.kt
> +data class SameName(
카카오 local api에서 제공하는 response의 클래스를 그대로 사용하고 있습니당
api 문서의 설명을 인용해서 말씀드리면,
질의어의 지역과 키워드 분석 정보를 담고 있는 클래스로
예를 들어, '중앙로 맛집'을 검색했을 때 '중앙로'에 해당하는 지역 리스트 정보와
질의어에서 지역 정보를 분리한 키워드인 '맛집' 키워드 정보를 담고 있는 클래스라고 보시면 될 것 같아요!
'중앙로'처럼 여러 지역에서 같은 이름으로 되어 있는 동네 이름..?들을 처리해 주기 위한 클래스기 때문에 same_name으로 네이밍 하지 않았을까 싶습니다..!

2021-11-22 11:38 UTC, LuvJoy commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/di/NetworkModule.kt
> +    @Singleton
모듈을 만들때 @InstallIn(SingletonComponent::class) 선언은
그 내부에 있는 친구들은 Singleton으로 만들어 주겠다라는 의미라
그래서 내부에 Singleton 어노테이션을 달아주지 않아도 됩니다!

2021-11-22 13:02 UTC, jihee-dev commented on DeliBuddy/data/src/main/java/yapp/android1/data/entity/AddressMapper.kt
> +    fun responseToAddress(keywordDocument: KeywordDocument): Address {
이 부분 때문에 데이터 레이어의 모델에는 Response를 붙여서 `ResponseAddress`, `ResponseKeyword`로 이름을 정하고, 도메인의 모델에는 그냥 `Address`로 정해서 구분을 하려고 했습니다..!
이런 네이밍 규칙도 정하면 좋을 것 같은데 어떻게 정하면 좋을까요? @LuvJoy @lin9703

2021-11-22 13:07 UTC, jihee-dev commented on DeliBuddy/data/src/main/java/yapp/android1/data/entity/AddressMapper.kt
> +object AddressMapper {
조금 헷갈릴 수도 있다고 느끼는 부분이 `AddressDocument`와 `KeywordDocument`를 둘 다 Address로 변환하는 부분이라서 바꾼다면 `AddressResponseMapper` 정도가 좋을 것 같은데 어떠신가요..?

2021-11-22 13:17 UTC, jsh-me commented on DeliBuddy/data/src/main/java/yapp/android1/data/entity/AddressMapper.kt
> +object AddressMapper {
너무 좋습니다! 편한방향으로 갑쉬다

2021-11-22 13:18 UTC, jsh-me commented on DeliBuddy/data/src/main/java/yapp/android1/data/entity/AddressMapper.kt
> +    fun responseToAddress(keywordDocument: KeywordDocument): Address {
팀에서 편한 방향으로 가도 괜찮을것 같아용 ㅎㅎ 반드시 코멘트를 반영해야하는건 아니니까요!

2021-11-22 13:20 UTC, jihee-dev commented on DeliBuddy/data/src/main/java/yapp/android1/data/entity/AddressMapper.kt
> +    fun responseToAddress(keywordDocument: KeywordDocument): Address {
좋아유 저희끼리 이런 네이밍에 대한 규칙을 정한 게 없던 것 같아서 이번 기회에 정하면 좋을 것 같아요!! 😆

2021-11-22 13:22 UTC, jihee-dev commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/ui/address/search/AddressSearchFragment.kt
> +                addressAdapter.updateResult(it)
어잌후.. 검색 결과에 빈 리스트로 보여주도록 되어 있는데 따로 검색에 실패했다는 내용을 사용자에게 알려주는 처리를 안 해 준 것 같네요..? 수정해 보겠습니다!

2021-11-22 13:45 UTC, jihee-dev commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/ui/address/search/AddressSearchFragment.kt
> +                    val address = addressAdapter.getItem(position)
리뷰를 보고 이런 식으로 고치는 게 좋을 것 같다는 생각이 들었는데,
제가 이해한 바로는
그렇게 하려면 뷰 홀더의 init 부분에서 클릭 리스너를 달아줄 때 position이 아니라 position에 해당하는 item 자체를 전달해 줄 수 있어야 한다 < 이렇게 이해했습니다..
그런데 뷰 홀더에서 포지션은 알 수 있지만 전체 아이템 리스트를 가지고 있지 않기 때문에 이걸 어떻게 전달할 수 있을지 잘 모르겠어요.. 😢
혹시 어떤 식으로 구현해야 할지 조언을 얻을 수 있을까요..?

2021-11-22 13:58 UTC, jihee-dev commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/di/NetworkModule.kt
> +    @Singleton
아하 이해했습니다!
그러면 레포지토리와 유즈케이스를 주입해 주는 부분,
그리고 미리 만들어져 있던 네트워크 모듈 주입해 주는 부분과
제가 추가로 작성한 부분에서 싱글톤 어노테이션을 제거하도록 하겠습니다!

2021-11-22 17:02 UTC, LuvJoy commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/ui/address/search/AddressSearchFragment.kt
> +                    val address = addressAdapter.getItem(position)
https://github.com/jihee-dev/simple-clean-architecture/commit/5520ba2d4d143680c65e5b0744759fe125a52ce0
저번에 답을 드린적이 있었네요 다시한번 보시는걸 추천드립니다

https://github.com/jihee-dev/simple-clean-architecture/pull/3

2021-11-22 18:24 UTC, jihee-dev commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/ui/address/search/AddressSearchFragment.kt
> +                    val address = addressAdapter.getItem(position)
아 그때와 같은 방법으로 해결 가능하겠네요..! 감사합니다 😃 이 부분 반영해서 수정했습니다!

2021-11-22 20:59 UTC, jihee-dev commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/ui/address/search/AddressSearchFragment.kt
> +                addressAdapter.updateResult(it)
해당 부분 수정 완료했습니당~!

2021-11-22 21:05 UTC, jihee-dev commented
리뷰 주신 부분들 반영해서 수정 완료했습니다!
아무 생각 없이 리뷰 하나당 커밋 하나로 했더니 쓸데없이 커밋 내역만 너무 많아졌네요 ㅠㅠ
에러 핸들링 부분을 까먹고 구현하지 않아서 이 부분도 추가했습니다!
최대한 잘해 보려고 하긴 했는데 맞게 잘 짠 건지 모르겠네요..
이 부분도 리뷰 해 주시면 다시 수정해 보겠습니다!

2021-11-23 03:19 UTC, LuvJoy commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/ui/address/search/AddressSearchViewModel.kt
> +        job = null
job을 캔슬시켜주는 코드하고 에러 핸들링 하는 구조는 제가 한번 더 개선하고
지희님이랑 오늘 저녁 스크럼때 같이 좋은방향 맞춰가는게 좋을거 같아요!

2021-11-23 03:19 UTC, LuvJoy commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/ui/address/search/AddressSearchViewModel.kt
> +        job = null
뭔가.. 제가 짠 Base가 좀 이상하다는 생각이 자꾸 들어서 그래요!

2021-11-23 03:20 UTC, LuvJoy commented on DeliBuddy/domain/src/main/java/yapp/android1/domain/interactor/usecase/SearchAddressUseCase.kt
>          val responseKeyword = addressRepository.searchAddressByKeyword(params)
편-안한 네이밍 좋습니다

2021-11-23 03:26 UTC, LuvJoy commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/holder/AddressSearchViewHolder.kt
> +        searchResultClickListener: ((Address) -> Unit)
null을 허용해주면 bind할때 !!를 안해줄 수 있어서 더 좋을거 같아요!
그리고 listener를 invoke할때는 ?. 으로 null값이면 아무 실행도 하지 않도록 하면 되기 때문입니다!

2021-11-23 03:26 UTC, LuvJoy commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/adapter/AddressSearchAdapter.kt
> +                searchResultClickListener!!
```suggestion
                item = getItem(position),
                searchQuery = resultPair.first,
                searchResultClickListener = searchResultClickListener!!
```

이렇게 힌트를 넣어주는것도 좋아요!

2021-11-23 03:27 UTC, LuvJoy approved these changes
새벽까지 고생 많으셨습니다! 🥇

2021-11-23 10:56 UTC, jihee-dev commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/ui/address/search/AddressSearchViewModel.kt
> +        job = null
좋습니다!

2021-11-23 15:38 UTC, merged