Fix: select address
YAPP-19th/Android-Team-1-Frontend pull request #45
Opened 2021-12-18 09:16 UTC by jihee-dev

### 위치 설정 변경 사항
- 디자인 변경 사항 적용
    - 현위치로 찾기 버튼 추가
    - 검색어 입력 시 버튼 사라지도록 수정
- 파티 주소 설정 시 선택한 주소 결과 받아오기
- 현 위치 찾기
    - GPS로 현위치 위경도 가져오기
    - 현위치 검색하기 버튼으로 이동했을 경우 처리
- 주소 상세 화면에서 지도에 현위치 버튼 추가

### 스플래시 관련
- 로그인 관련 코드 분리 → 스플래시에서도 로그인 확인이 필요하기 때문에 분리 필요함

### 홈 화면 유저 주소 변경 처리
→ 이 부분 세희 님께서 저번에 해 주시긴 했는데 합치면서 문제가 생겨서 다시 수정했어요!
- 홈 화면에서 주소 보이도록 수정
- 홈 화면에서 주소 저장하도록 수정

2021-12-18 09:46 UTC, LuvJoy commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/ui/address/AddressSharedViewModel.kt
>      val isActivate: EventFlow<Boolean> = _isActivate
이 부분은 왜 var 인가요?

2021-12-18 09:48 UTC, jihee-dev commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/ui/address/AddressSharedViewModel.kt
>      val isActivate: EventFlow<Boolean> = _isActivate
오우 실수입니다..! 고쳐야겠네요!! 감사합니다!

2021-12-18 09:50 UTC, LuvJoy commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/ui/home/viewmodel/PartiesViewModel.kt
> +    val saveAddressEvent: StateFlow<SaveAddressEvent> = _saveAddressEvent
요 부분도 var도 실수일까요?? 아니면 의도하신건가유?

2021-12-18 09:51 UTC, jihee-dev commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/ui/home/viewmodel/PartiesViewModel.kt
> +    val saveAddressEvent: StateFlow<SaveAddressEvent> = _saveAddressEvent
실수입니다.. 왜 저 친구들 단체로 var로 되어 있는 걸까요...

2021-12-18 09:52 UTC, LuvJoy commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/util/user/UserManager.kt
> +        }
그냥 함수로 빼는게 좋을것 같아요!

2021-12-18 10:06 UTC, LuvJoy commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/util/user/UserManager.kt
> +class UserManager(
하나의 클래스로 깔끔하게 묶으려고 하신것 같은데 
이 클래스가 과연 필요할까에 대한 의문이 듭니다!
UserManager라는 추상적인 이름 또한 그렇고 이 기능들을 재사용이 필요한 곳이 있는 것도 아닙니다

또한 하나의 의존성이 늘어남에 따라 수정이 있을경우 이 부분 또한 수정을 해야하기 때문에
굳이 이 부분을 이렇게 해야하나 생각이드네요!

2021-12-18 10:15 UTC, LuvJoy requested changes
한 PR이 너무 많아서 다 읽지는 못할것 같네요.. 
우선 보이는것들만 리뷰 드렸습니다

2021-12-18 10:16 UTC, jihee-dev commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/util/user/UserManager.kt
> +class UserManager(
음 실제로 스플래시에서 로그인 여부를 확인해야 해서 재사용이 필요하다고 판단했는데 어떻게 생각하시나요?

2021-12-18 10:19 UTC, jihee-dev commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/util/user/UserManager.kt
> +        }
좋아요 수정해 보겠습니다!

2021-12-18 10:21 UTC, lin9703 commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/ui/splash/SplashActivity.kt
> +    private fun checkLoginAndIntent() {
splash에서 카카오 로그인을 해주는 이유가 있을까요?!

2021-12-18 10:21 UTC, lin9703 commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/ui/login/LoginActivity.kt
> +                    false -> AuthViewModel.AuthEvent.OnKakaoLoginFailed("다시 시도해 주세요.")
이건 그냥 궁금해서 묻는 건데 혹시 if에서 when을 사용한 이유가 있을까요?

2021-12-18 10:21 UTC, lin9703 commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/ui/login/viewmodel/AuthViewModel.kt
> +                userManager.setDeliBuddyAuth(auth)
LoginActivity의 collectData() 함수의 값과 중복된 이유가 있을까요?

2021-12-18 10:23 UTC, LuvJoy commented
SelectAddress PR에 Login부분도, Home부분이 있고 해서 많이 혼란스럽네요!

2021-12-18 10:24 UTC, LuvJoy commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/ui/login/LoginActivity.kt
> +                    false -> AuthViewModel.AuthEvent.OnKakaoLoginFailed("다시 시도해 주세요.")
동일한 의견인데 When 개인취향이긴 하지만
뎁스가 늘어나서 코드가 못생겨지기 때문에 고려해야될 케이스가 많을때 when을 사용하는게 어떨까 싶어요!

2021-12-18 10:30 UTC, LuvJoy commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/util/user/UserManager.kt
> +class UserManager(
jwt토큰의 유무를 확인하고 있다면 해당 토큰이 유효한지만 확인만 하면되지 않을까 싶어요!

2021-12-18 10:32 UTC, jihee-dev commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/ui/splash/SplashActivity.kt
> +    private fun checkLoginAndIntent() {
로그인 액티비티의 경우 가입 정보가 없을 때 가입하기 위한 화면이라고 판단했습니다
버튼도 카카오로 로그인하기라고 되어 있는 게 아니라 카카오로 시작하기라고 되어 있어서요!
가입과 로그인이 되어 있는 상황이라면 스플래시에서 체크한 뒤에
추가로 과정 없이 홈 화면으로 이동하는 게 맞다고 생각했어요!

2021-12-18 10:33 UTC, LuvJoy commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/util/user/UserManager.kt
> +class UserManager(
아 한가지 더 말씀드릴건
Class를 나눌때는 한 가지만 명확히 하는게 좋다고 생각해요! 해당 UserManager클래스는 KakaoLogin기능을 담기도 하고
SharedPreference기능을 하기도 하는데
차라리 UserLoginManager 클래스를 만들고  UserLoginManager에서 SharedPreference 기능이 동작하게끔 하고
KakaoLogin기능 부분들은  KakaoLoginModule클래스로 로 분리해서 처리하는게 더욱 깔끔하다고 생각합니다

2021-12-18 10:55 UTC, jihee-dev commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/ui/home/viewmodel/PartiesViewModel.kt
> +    val saveAddressEvent: StateFlow<SaveAddressEvent> = _saveAddressEvent
@jsh-me 엇 이 부분은 확인해 보니 세희 님 코드를 위치만 옮긴 부분이어서 그대로 가져온 것 같아요! 이거 val로 수정해도 괜찮을까요?

2021-12-18 10:57 UTC, jihee-dev commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/ui/home/viewmodel/PartiesViewModel.kt
> +    val saveAddressEvent: StateFlow<SaveAddressEvent> = _saveAddressEvent
위치를 옮겼던 이유는 유저의 주소를 저장하는 것을 홈으로 옮겨주면서 하게 되었습니다!
현재의 주소 선택 화면은 주소를 선택하기 위한 화면일 뿐
선택된 주소를 저장할지, 아니면 파티의 주소로 지정하게 될지는 결과를 받은 곳에서 처리해 주어야 한다고 생각했어요!

2021-12-18 11:05 UTC, jihee-dev commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/util/user/UserManager.kt
> +class UserManager(
sharedPreference 기능이 로그인 관련된 정보만 포함해서 로그인과 관련된다고 생각했어요!
그런데 추후에 또 다른 로그인이 추가되었을 때를 생각해 보면 카카오로그인으로 따로 분리해 두는 게 좋을 것 같네요
변경해 보겠습니다!

2021-12-18 11:17 UTC, jihee-dev commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/ui/login/viewmodel/AuthViewModel.kt
> +                userManager.setDeliBuddyAuth(auth)
요고는 혹시 무슨 말씀이신가요 제가 이해를 하지 못했어요 ㅠㅠ

2021-12-18 11:51 UTC, lin9703 commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/ui/login/LoginActivity.kt
> +                    userManager.setDeliBuddyAuth(auth)
요 부분과 중복된다는 말이었습니다~! 하나만 있어도 되지 않을까? 싶었어요~

2021-12-18 11:52 UTC, lin9703 commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/ui/login/viewmodel/AuthViewModel.kt
> +                userManager.setDeliBuddyAuth(auth)
밑에 코멘트 남겼습니다~

2021-12-18 11:57 UTC, jihee-dev commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/ui/login/LoginActivity.kt
> +                    userManager.setDeliBuddyAuth(auth)
오 그러네요?! 그러면 혹시 로그인 액티비티에서 intent만 하도록 수정해도 괜찮을까요?

2021-12-19 12:36 UTC, lin9703 commented on DeliBuddy/app/src/main/java/yapp/android1/delibuddy/ui/login/LoginActivity.kt
> +                    userManager.setDeliBuddyAuth(auth)
앗 이건 제 개인 취향인데 액티비티로 받았을 때 저장되는 게 좋지 않을까요? 
그러면 굳이 tokenResult에 token 값을 저장하는 이유가 없지 않을까요?

2021-12-22 15:07 UTC, LuvJoy approved these changes

2021-12-22 15:43 UTC, merged